project:
  type: website
  output-dir: docs

website:
  title: "Hamidreza Moaddeli"
 
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/moaddeli/

      - icon: github
        href: https://www.github.com/moaddeli

      - icon: twitter 
        href: https://twitter.com/hrmoaddeli
    background: primary
    left:
      - href: index.qmd
        text: Home    
      - href: cv.qmd
        text: CV  
      - href: links.qmd  
        text: Links
      - href: posts
        text: Blog
       
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
   




